import type { ToolConfig } from '@/components/ToolProcessor';

export const toolsConfig: Record<string, ToolConfig> = {
  'merge-pdf': {
    id: 'merge-pdf',
    title: 'Merge PDF',
    desc: 'Combine multiple PDF files into one document, in the order you choose.',
    accept: '.pdf',
    multiple: true,
    gradient: 'from-blue-500 to-blue-600',
    icon: '⚡',
    inputLabel: 'Select PDF files to merge',
  },
  'split-pdf': {
    id: 'split-pdf',
    title: 'Split PDF',
    desc: 'Split a PDF into multiple files by page ranges.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-violet-500 to-purple-600',
    icon: '✂️',
    inputLabel: 'Select a PDF to split',
    options: [
      {
        key: 'range',
        label: 'Page ranges (e.g. 1-3, 5, 7-9) — leave blank to split every page',
        type: 'text',
        placeholder: '1-3, 5, 7-9',
        defaultValue: '',
      },
    ],
  },
  'compress-pdf': {
    id: 'compress-pdf',
    title: 'Compress PDF',
    desc: 'Reduce the file size of your PDF while maintaining quality.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-emerald-500 to-teal-600',
    icon: '🗜️',
    inputLabel: 'Select a PDF to compress',
  },
  'rotate-pdf': {
    id: 'rotate-pdf',
    title: 'Rotate PDF',
    desc: 'Rotate all pages of your PDF by 90°, 180°, or 270°.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-indigo-500 to-violet-600',
    icon: '↻',
    inputLabel: 'Select a PDF to rotate',
    options: [
      {
        key: 'angle',
        label: 'Rotation angle',
        type: 'select',
        defaultValue: '90',
        options: [
          { value: '90', label: '90° Clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '90° Counter-clockwise' },
        ],
      },
    ],
  },
  'jpg-to-pdf': {
    id: 'jpg-to-pdf',
    title: 'JPG to PDF',
    desc: 'Convert one or multiple JPG images into a single PDF document.',
    accept: '.jpg,.jpeg',
    multiple: true,
    gradient: 'from-orange-400 to-yellow-500',
    icon: '🖼️',
    inputLabel: 'Select JPG images',
  },
  'png-to-pdf': {
    id: 'png-to-pdf',
    title: 'PNG to PDF',
    desc: 'Convert PNG images into a PDF document.',
    accept: '.png',
    multiple: true,
    gradient: 'from-purple-500 to-pink-500',
    icon: '🎨',
    inputLabel: 'Select PNG images',
  },
  'webp-to-pdf': {
    id: 'webp-to-pdf',
    title: 'WebP to PDF',
    desc: 'Convert WebP images to PDF format.',
    accept: '.webp',
    multiple: true,
    gradient: 'from-teal-500 to-cyan-500',
    icon: '🌐',
    inputLabel: 'Select WebP images',
  },
  'image-to-pdf': {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    desc: 'Convert any image (JPG, PNG, WebP) to PDF.',
    accept: '.jpg,.jpeg,.png,.webp',
    multiple: true,
    gradient: 'from-orange-500 to-amber-600',
    icon: '🖼️',
    inputLabel: 'Select images (JPG, PNG, WebP)',
  },
  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    title: 'PDF to JPG',
    desc: 'Convert each PDF page into a high-quality JPG image.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-yellow-500 to-orange-500',
    icon: '📸',
    inputLabel: 'Select a PDF to convert',
  },
  'pdf-to-png': {
    id: 'pdf-to-png',
    title: 'PDF to PNG',
    desc: 'Convert each PDF page into a lossless PNG image.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-purple-500 to-violet-600',
    icon: '🖼️',
    inputLabel: 'Select a PDF to convert',
  },
  'watermark': {
    id: 'watermark',
    title: 'Add Watermark',
    desc: 'Add a text watermark to every page of your PDF.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-sky-500 to-blue-600',
    icon: '💧',
    inputLabel: 'Select a PDF to watermark',
    options: [
      {
        key: 'text',
        label: 'Watermark text',
        type: 'text',
        placeholder: 'CONFIDENTIAL',
        defaultValue: 'CONFIDENTIAL',
      },
    ],
  },
  'page-numbers': {
    id: 'page-numbers',
    title: 'Add Page Numbers',
    desc: 'Automatically number every page of your PDF.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-pink-500 to-rose-600',
    icon: '#',
    inputLabel: 'Select a PDF',
    options: [
      {
        key: 'position',
        label: 'Number position',
        type: 'select',
        defaultValue: 'bottom-center',
        options: [
          { value: 'bottom-center', label: 'Bottom Center' },
          { value: 'bottom-right', label: 'Bottom Right' },
          { value: 'bottom-left', label: 'Bottom Left' },
        ],
      },
    ],
  },
  'protect-pdf': {
    id: 'protect-pdf',
    title: 'Protect PDF',
    desc: 'Password-protect your PDF to restrict access.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-red-500 to-rose-600',
    icon: '🔒',
    inputLabel: 'Select a PDF to protect',
    options: [
      {
        key: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Enter a strong password',
        defaultValue: '',
      },
    ],
  },
  'unlock-pdf': {
    id: 'unlock-pdf',
    title: 'Unlock PDF',
    desc: 'Remove password protection from a PDF.',
    accept: '.pdf',
    multiple: false,
    gradient: 'from-green-500 to-emerald-600',
    icon: '🔓',
    inputLabel: 'Select a protected PDF',
    options: [
      {
        key: 'password',
        label: 'Current password (leave blank if none)',
        type: 'password',
        placeholder: 'Enter PDF password',
        defaultValue: '',
      },
    ],
  },
};
